"$schema" = 'https://starship.rs/config-schema.json'

[aws]
  symbol = '☁️ '

[directory]
  truncate_to_repo  = false
  truncation_symbol = "../"

[nodejs]
  disabled = false

[os]
  disabled = false

[localip]
  disabled = false
  ssh_only = false

[time]
  disabled = false

[username]
  show_always = true
