"$schema" = 'https://starship.rs/config-schema.json'

[aws]
  disabled = true
  symbol   = '☁️ '

[directory]
  truncate_to_repo  = false
  truncation_symbol = "../"

[nodejs]
  disabled = false

[os]
  disabled = false

[time]
  disabled = true

[username]
  show_always = true
