[main]
dpi-aware = no
fields = name,generic,comment,categories,filename,keywords
terminal = alacritty
prompt = " " 
placeholder = "Search..."
icons-enabled = yes
show-actions = yes
anchor = center
width = 64
horizontal-pad = 16
vertical-pad = 16
inner-pad = 8
line-height = 20
exit-on-keyboard-focus-loss = yes
show-actions = yes
match-counter = yes
use-bold = yes
enable-mouse = yes

[colors]
background = 383c4aff
text = ffffffff
# match = 9ece6aff
selection = 374969ff
selection-text = ffffffff
border = 7aa2f7ff

[border]
width = 2
radius = 128
