[window]
  padding.x = 8
  padding.y = 8

[font]
  bold.style          = "Bold"
  bold_italic.style   = "Bold Italic"
  builtin_box_drawing = true
  glyph_offset.x      = 0
  glyph_offset.y      = 0
  italic.style        = "Italic"
  normal.family       = "JetbrainsMono Nerd Font"
  normal.style        = "Regular"
  size                = 12


[colors.bright]
  black   = "#686868"
  blue    = "#57c7ff"
  cyan    = "#9aedfe"
  green   = "#5af78e"
  magenta = "#ff6ac1"
  red     = "#ff5c57"
  white   = "#f1f1f0"
  yellow  = "#f3f99d"

[colors.normal]
  black   = "#282a36"
  blue    = "#57c7ff"
  cyan    = "#9aedfe"
  green   = "#5af78e"
  magenta = "#ff6ac1"
  red     = "#ff5c57"
  white   = "#ffffff"
  yellow  = "#f3f99d"

[colors.primary]
  background = "#282a36"
  foreground = "#eff0eb"

[cursor]
  style.blinking = "On"
  style.shape    = "Block"

[terminal]

  [terminal.shell]
    program = "/bin/zsh"
